
<div id="navegacion" prev="../Ejercicios_Tema_7/ej6.html" next=""></div>

<div class="section-title">Section 6.5</div>

#  Movilens 1M


Movilens Dataset collects data from 6,000 users and 4,000 movies. The information is
distributed in 3 tables.

- [ratings.dat](./ml-1m/ratings.dat) - The file collects user rating data. The columns are: User, MovieID, Rating, Date.

- [movies.dat](./ml-1m/movies.dat) - Movie data. The columns are: MovieID, Title, Genre
- [users.dat](./ml-1m/users.dat) - Personal data of users. The columns are: User, Gender, Age, Occupation,
ZipCode.


Personal data of users. The columns are: User, Gender, Age, Occupation,
ZipCode.
All this information is used very frequently in recommender systems that apply learning
algorithms. Information on the content of the files can be found in the [README](./ml-1m/README) link.

## Import data

Create a DataFrame for each of the files. Use the function `head()` to display the first data. The
ratings file has a date type field. Use the parameter `parse_dates` to properly load the dates.

In [ ]:
# Sol:

## X-Men ratings

Users rate the movies with values from 1 to 5 where 1 is the worst score and 5 is the best. The
score is a categorical variable. Find the number of votes of each type (the frequency of votes)
for the movie entitled `X-Men (2000)`.

In [ ]:
# Sol:

## Average score

Calculate the average score of each movie by user gender. Design a function called
`puntuacion_media` that returns a Dataframe where the index is the movie title and the columns
are 'F' and 'M' (Female and Male respectively).

__Remark__:

There are several ways to do it. Here are some suggestions:
* We need to combine the three tables since we have, on the one hand, the ratings, on the
other the title of the movie and on the other the gender of the users. The operation
`merge` will allow you to perform the combination. 
    * First match the ratings with the movies by the 'id_peli' field.
    * Combine the above result with the users by the 'id_usuario' field.
    
* Once the three tables have been combined into a single table:
    * solution 1:  Group by `id_peli` and user `sexo` (genre). The aggregation function is the mean `mean()`. To get the requested table use `unstack` to undo the multi index.
    * solution 2: Check the doc for function `pivot_table`. Use the function `pivot_table`. It is
worth trying to solve it also using this option.

In [ ]:
# Sol:
def puntuacion_media():
    """Compute the average score by movie and user genre
    
    Example:
        >>> puntuacion_media()
               
        genero_u                            F          M
        titulo 
        $1,000,000 Duck (1971)       3.375000    2.761905
        'Night Mother (1986)         3.388889    3.352941
        'Til There Was You (1997)    2.675676    2.733333

        ...
        ...

"""